export const PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";

export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
 export const PATCH_PRODUCT_SUCCSSESS="PATCH_PRODUCT_SUCCSSESS"